<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Jobs\**" />
    <Content Remove="Jobs\**" />
    <EmbeddedResource Remove="Jobs\**" />
    <None Remove="Jobs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="MassTransit" Version="8.3.3" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.3.3" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="Pgvector.EntityFrameworkCore" Version="0.3.0" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.18.1" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.1" />
    <PackageReference Include="Quartz.Serialization.Json" Version="3.18.1" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Files\Galaxy_S24_Manual.pdf" />
    <None Include="wwwroot\Files\PS5_Manual.pdf" />
    <None Include="wwwroot\Files\Sharp_Ac_Manual.pdf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ManualMate.Application\ManualMate.Application.csproj" />
    <ProjectReference Include="..\ManualMate.Infrastructure\ManualMate.Infrastructure.csproj" />
  </ItemGroup>

</Project>
