using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ManualMate.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class ChangeItemIdToGuid : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_FileEmbeddings_Items_ItemId",
                table: "FileEmbeddings");

            migrationBuilder.Sql(
                "ALTER TABLE \"Items\" ALTER COLUMN \"Id\" DROP IDENTITY;");

            migrationBuilder.Sql(
                "ALTER TABLE \"FileEmbeddings\" ALTER COLUMN \"ItemId\" TYPE uuid " +
                "USING (md5('item-' || \"ItemId\")::uuid);");

            migrationBuilder.Sql(
                "ALTER TABLE \"Items\" ALTER COLUMN \"Id\" TYPE uuid " +
                "USING (md5('item-' || \"Id\")::uuid);");

            migrationBuilder.AddForeignKey(
                name: "FK_FileEmbeddings_Items_ItemId",
                table: "FileEmbeddings",
                column: "ItemId",
                principalTable: "Items",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_FileEmbeddings_Items_ItemId",
                table: "FileEmbeddings");

            migrationBuilder.Sql(
                "TRUNCATE TABLE \"FileEmbeddings\", \"Items\" CASCADE;");

            migrationBuilder.Sql(
                "ALTER TABLE \"FileEmbeddings\" ALTER COLUMN \"ItemId\" TYPE integer;");

            migrationBuilder.Sql(
                "ALTER TABLE \"Items\" ALTER COLUMN \"Id\" TYPE integer;");

            migrationBuilder.Sql(
                "ALTER TABLE \"Items\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.AddForeignKey(
                name: "FK_FileEmbeddings_Items_ItemId",
                table: "FileEmbeddings",
                column: "ItemId",
                principalTable: "Items",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
